### ISSUE TITLE
 Couldn't scrape ad: Error: No ad bounding box

### ISSUE THREAD

**Issue by sana-17** [UWCSESecurityLab/adscraper#5]
On almost all weather websites i tried to crawl, the following error keeps coming up :- 
 "Couldn't scrape ad: Error: No ad bounding box"
I do not intend  to take screenshots of ads, i only need to collect the ad URLs, preferably not just the initial URL but the resolved one. I've tried both "clickAndBlockLoad" and "clickAndScrapeLandingPage" options but i keep bumping into the above error. 
Also tried adjusting the bounding box pixels to as low as 1, still no success. Any suggestions on how to fix this would be greatly appreciated.

**Comment by eric-zeng** [comment]
This is a warning message that occurs fairly commonly, but almost all of the time it isn't your fault, nor is it an issue with the crawler. It typically happens when a website has ad slots that aren't ever filled and rendered (i.e. an HTML element for mobile ads that aren't filled on desktop), but the ad detector marks it as an ad, because the element's classes are caught by the query selector. In these cases, the size of the element is 0x0, and no ad actually exists (and thus we cannot click or screenshot the ad). 

You can verify this by running the crawler in headful mode (set 'headless: false' in chromeOptions) - and check when the crawler is pausing, whether it has actually centered a real ad on the screen. If this is not the case and there is a rendered ad that is not being captured, please reopen the issue.
